name: cegames
description: "Central Events Games Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router: ^14.0.1
  flutter_dotenv: ^5.1.0
  percent_indicator: ^4.2.3
  iconly: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  desktop_multi_window: ^0.2.0
  flutter_secure_storage: ^9.0.0
  desktop_lifecycle: ^0.1.1
  oktoast: ^3.4.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  path_provider: ^2.1.3
  file_selector: ^1.0.3
  file_picker: ^8.0.3
  flutter_dialogs: ^3.0.0
  flutter_material_color_picker: ^1.2.0
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/icons/ic-app-bg.png"
  android: false
  ios: false
  web: 
    generate: false
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

flutter_native_splash:
  image: assets/icons/ic-app.png
  color: "#000000"
  web: false
  android: false
  ios: false

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - .env
      - assets/icons/
      - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Platypi
      fonts:
        - asset: assets/fonts/Platypi.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Raleway-Regular
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Raleway-Medium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Raleway-ExtraBold
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
